import _ from "lodash";
import { Meteor } from "meteor/meteor";
import "/imports/api/courses";
import "/imports/api/students/students";
import "/imports/api/registrations";
import "/imports/api/students/server/publications";
import "/imports/api/courses/server/publications";
import "/imports/api/registrations/server/publications";
import "/imports/startup/users";
import "/imports/startup/courses";
import "/imports/startup/students";
